package headsetvolume

import (
	"encoding/binary"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// Generated by the original 1.11.0 GET_DESCRIPTOR handlers for USB personality 2
// and stereo variant 0x87, with one HID interface. This is protocol descriptor
// data, not executable firmware or a claimed capture from the reporter's unit.
// Firmware SHA256: 2b7b47731439c31d0f5e212c569aca7db8f34fa674f6d9f9731f63a117bbea48.
func originalDescriptorFixture(t *testing.T) []byte {
	t.Helper()
	data, err := hex.DecodeString(
		"12010002000000080e0b360e110101020301090211010401008032090400000001010000" +
			"0a2401000169000201020c24020a01020002030000060c24020402040301040000040924" +
			"060504010300040924030601010005040c24020101010002030000050a24060208010300" +
			"0005092406070a010300060d240408020107020300000005092403030204040205090401" +
			"000001020000090401010101020000072401060101001424020101021004401f00803e00" +
			"44ac0080bb000905820d6200010000072501010101000904020000010200000904020101" +
			"01020000072401010101001724020102021005401f00803e00007d0044ac0080bb000905" +
			"020dc4000100000725010101010009040300010300000009211101000122860107058103" +
			"400001")
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func descriptorUnit(t *testing.T, data []byte, id byte) []byte {
	t.Helper()
	for off := 27; off < len(data); off += int(data[off]) {
		item := data[off : off+int(data[off])]
		if len(item) >= 4 && item[1] == 0x24 && item[2] >= 2 && item[2] <= 8 && item[3] == id {
			return item
		}
	}
	t.Fatalf("unit %d missing from fixture", id)
	return nil
}

func TestOriginalFirmwarePlaybackDescriptor(t *testing.T) {
	info, err := Inspect(originalDescriptorFixture(t))
	if err != nil || info.Interface != 0 || info.Channels != 2 || !info.AdvertisedVolume {
		t.Fatalf("original firmware's mixer-to-headset topology was rejected: %#v, %v", info, err)
	}
}

func TestTruncatedPlaybackDescriptors(t *testing.T) {
	original := originalDescriptorFixture(t)
	for size := 0; size < len(original); size++ {
		data := append([]byte(nil), original[:size]...)
		if len(data) >= 27 {
			binary.LittleEndian.PutUint16(data[20:], uint16(size-18))
		}
		// Ending exactly at a complete descriptor after the audio control block
		// is harmless: unrelated streaming/HID descriptors do not set the volume.
		_, err := Inspect(data)
		if err != nil {
			var descriptorErr *DescriptorError
			if !errors.As(err, &descriptorErr) {
				t.Fatalf("size %d: rejection cannot be reported safely: %v", size, err)
			}
		}
	}
}

func TestCachedOriginalDescriptorsAndDetailedRejection(t *testing.T) {
	root := t.TempDir()
	data := originalDescriptorFixture(t)
	for name, contents := range map[string][]byte{
		"idVendor": []byte("0b0e"), "idProduct": []byte("0e36"), "bcdDevice": []byte("0111"),
		"busnum": []byte("1"), "devnum": []byte("2"), "descriptors": data,
	} {
		if err := os.WriteFile(filepath.Join(root, name), contents, 0600); err != nil {
			t.Fatal(err)
		}
	}
	attachment, err := Capture(root)
	if err != nil {
		t.Fatal(err)
	}
	if info, err := attachment.Descriptor(); err != nil || info.Channels != 2 {
		t.Fatal("cached descriptor path rejected original firmware", info, err)
	}
	descriptorUnit(t, data, 2)[4] = 1
	if err := os.WriteFile(filepath.Join(root, "descriptors"), data, 0600); err != nil {
		t.Fatal(err)
	}
	_, err = attachment.Descriptor()
	var descriptorErr *DescriptorError
	if !errors.As(err, &descriptorErr) || descriptorErr.Error() != "unexpected headset playback feature unit 2; expected source mixer 8 and master mute" {
		t.Fatal("missing specific, safe rejection", err)
	}
}
